# Generated by Django 4.1 on 2022-10-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='mobile',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='mobile_colors', to='products.mobile'),
        ),
    ]
