# Generated by Django 4.1 on 2022-11-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_choices_mobile_laptop_choices_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='laptop',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_colors', to='products.laptop'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='mobile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_colors', to='products.mobile'),
        ),
    ]
